### ISSUE TITLE
huggingface device_map="auto" doesn't work for multi-gpu

### ISSUE THREAD

**Issue by lithafnium** [modal-labs/modal-client#1166]
Hey there! I'm trying to get a simple LLM example going with multiple gpus, but for some reason when using `device_map="auto"` I run into cuda errors. The model works fine when I only use 1 gpu. Any ideas? 

Here's the example I'm using: 

```
import time

from modal import Image, method, gpu, Stub
from pathlib import Path

huggingface_model_registry = {
    "vicuna": "lmsys/vicuna-7b-v1.5",
}

    
stub = Stub(name="test")

def download_model():

    from transformers import AutoModelForCausalLM

    # download all models
    for _, model in huggingface_model_registry.items(): 
        model = AutoModelForCausalLM.from_pretrained(
            model,
            token="...",
            trust_remote_code=True
        )

stub.container_image = (
    Image.debian_slim(python_version="3.10")
    # .apt_install("git", "gcc", "clang", "build-essential")
    .apt_install("git")
    # .env({
    #     "CUDA_LAUNCH_BLOCKING": "1",
    #     "TORCH_USE_CUDA_DSA": "1"
    # })
    .pip_install(
        "scipy",
        "protobuf==3.20.*",
        "accelerate~=0.25",
        "transformers",
        "torch",
        "torchvision",
        "torchaudio",
        "openai",
        "tqdm",
        "pyyaml", 
        "vllm==0.2.6", 
        "anthropic",
        "pandas", 
        "sentence-transformers",
        "numpy", 
        "pytz", 
        "wandb",
        "fschat[model_worker,webui]",
        "einops",
        "google-generativeai")
    .run_function(download_model)
)


@stub.cls(image=stub.container_image, gpu=gpu.A100(memory=80), container_idle_timeout=300)
class Vicuna:
    def __enter__(self):

        import torch
        from transformers import AutoTokenizer, AutoModelForCausalLM

        self.model_name = "lmsys/vicuna-7b-v1.5"
        print("loading tokenizer")
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name, token="...")
        print("loading model")
        self.llm = AutoModelForCausalLM.from_pretrained(
            self.model_name,
            trust_remote_code=True,
            torch_dtype=torch.float16,
            device_map="auto",
            token="..."
        )

        # self.llm.eval()

        self.max_tokens = 500
        self.temperature = 1
        self.top_p = 0.7
            
    @method()
    async def generate(self, input, history=[]):
        inputs = ["test"] * 10
        input_ids = self.tokenizer(
            inputs,
            return_tensors="pt",
            padding=True).to("cuda")

        print("generating....")
        output_ids = self.llm.generate(
                **input_ids,
                max_new_tokens=self.max_tokens,
                temperature=self.temperature,
                top_p=self.top_p,
                do_sample=self.temperature != 0)
        print("finished generating...")

        if not self.llm.config.is_encoder_decoder:
            output_ids = output_ids[:, input_ids["input_ids"].shape[1]:]
        
        completion_texts = self.tokenizer.batch_decode(output_ids, skip_special_tokens=True)

        return completion_texts
        
@stub.local_entrypoint()
def main(input: str):
    llm = Vicuna()
    sentence = llm.generate.remote(input)
    print(sentence)
    return sentence


```

Changing the gpu count results in the following error: 
```
RuntimeError: CUDA error: mapping of buffer object failed
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
, and compiling with those flags on doesn't help either. Can confirm the model works on the cpu alone.

**Comment by thundergolfer** [comment]
Hey @lithafnium, this could be a runtime issue on our part, affecting multi-GPU applications. We're actively working on it, and thank you for the reproduction script. 
If you reach out in our Slack, https://modal.com/slack, I can put your workspace on our legacy runtime to unblock you.

**Comment by thundergolfer** [comment]
Hey @lithafnium, using your script I can confirm that it works on our legacy runtime. Please reach out with your workspace name and I'll enable the legacy runtime for your workspace. 

In the meantime, we're working on the issue.

**Comment by thundergolfer** [comment]
@lithafnium we've merged a fix for this, and checked that your reproduction script now works with this multi-GPU configuration: `@stub.cls(image=stub.container_image, gpu=gpu.A100(count=2, memory=80), container_idle_timeout=300)`

Closing this issue as fixed :)

**Comment by anubhavghildiyal** [comment]
Hi @lithafnium ,
I am new to Modal. Where are the model weights stored when you run "download_model" at image creation time? Is this in some volume? 
Thanks
